what is OS ?
software that manage hardware resources for other applications

kernel
part of OS for managing hardware

processor single core 
context switching

What is Process ?
we can apps or program -> process
Process is unit of execution that has memory

process object in node js code
spawning a process

What is  Thread ?
process creates Thread
Worker threads
concurrency
parallelism

Node js multi threaded
Can a process exist without a thread ?
DEbugging worker threads

Environment variables
-system variables
-user
-process

exec command in node js 